package jm.task.core.jdbc.dao;

import jm.task.core.jdbc.model.User;
import jm.task.core.jdbc.util.Util;
import org.hibernate.Session;

import javax.persistence.Query;
import java.util.List;

public class UserDaoHibernateImpl implements UserDao {
    public UserDaoHibernateImpl() {

    }


    @Override
    public void createUsersTable() {
        final String sql = "create table if not exists users(" +
                "user_id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY," +
                "name varchar(50)," +
                "lastname varchar(50)," +
                "age smallint" +
                ");";
        try(Session session = Util.getSession()) {
            session.beginTransaction();
            session.createSQLQuery(sql).executeUpdate();
            session.getTransaction().commit();
        }
    }

    @Override
    public void dropUsersTable() {
        String sql = "drop table if exists users";
        try(Session session = Util.getSession()) {
            session.beginTransaction();
            session.createSQLQuery(sql).executeUpdate();
            session.getTransaction().commit();

        }
    }

    @Override
    public void saveUser(String name, String lastName, byte age) {
        User user = new User(name, lastName, age);
        //String hql = "INSERT INTO User";
        try(Session session = Util.getSession()) {

            session.beginTransaction();
            session.save(user);
            session.getTransaction().commit();
        }
    }

    @Override
    public void removeUserById(long id) {

        String hql = "DELETE User WHERE id = :id";

        try(Session session = Util.getSession()) {
            session.beginTransaction();
            Query query = session.createQuery(hql);
            query.setParameter("id", id).executeUpdate();
            session.getTransaction().commit();

        }
    }


    @Override
    public List<User> getAllUsers() {

        List<User> users = null;
        String hql = "SELECT u FROM User u";

        try(Session session = Util.getSession()) {
            users = session.createQuery(hql, User.class).list();
        }
        return users;
    }

    @Override
    public void cleanUsersTable() {

        String sql = "TRUNCATE table users";
        try(Session session = Util.getSession()) {
            session.beginTransaction();
            session.createSQLQuery(sql).executeUpdate();
            session.getTransaction().commit();

        }

    }
}
